# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Henry Berwick
description: "Hello and welcome to my portfolio! My name is Henry, and I'm a Data Scientist. Below you will find a range of interesting projects, which I have recently undertaken. Each of these has a strong emphasis on business impact, and showcases my skills as a Data Scientist, such as Data Visualisation, Python, AB Testing, Machine Learning, Deep Learning, and more. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/Henry_Berwick_CV.docx
avatar_image: /img/profile_picture_square_colour.jpg

#-------------------------------
# Contact links
linkedin: "https://www.linkedin.com/in/henry-berwick/"
github: "https://github.com/HJBerwick"

paginate: 12
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

